version: '3'
services:
  front:
    container_name: front
    hostname: front
    build:
      context: ./front
      dockerfile: dev.dockerfile
    volumes:
      - ./front:/usr/front
      - /usr/front/node_modules
    environment:
      - PORT=80
      - NODE_ENV=development

  front-balancer:
    container_name: front-balancer
    hostname: front-balancer
    image: nginx:alpine
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
    volumes:
      - ./config/front-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front/static:/var/www/static
    depends_on:
      - front
